### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by linuxdaemon** [snoonetIRC/website#70] opened 2019-04-09 13:49 UTC
Found via `wget --spider -r https://snoonet.org`

```
Found 8 broken links.

https://snoonet.org/bloodygonzo
https://snoonet.org/TrollChromosomes
https://snoonet.org/helpop/umodes
https://snoonet.org/aspergersrules
https://snoonet.org/vol
https://snoonet.org/community/depression/findtreatment.samhsa.gov
https://snoonet.org/webchat
https://snoonet.org/community/depression/resources
```

**Comment by n7st** [comment] 2019-04-13 08:30
* https://snoonet.org/bloodygonzo - need to add a "hidden" or ex-staff page type for alumni and put the content for gonzo's staff page back
* https://snoonet.org/TrollChromosomes - could be caused by the Hugo version change? Will check after next deploy
* https://snoonet.org/helpop/umodes - Page is at /umodes - add alias (or move to subdirectory of helpop)
* https://snoonet.org/aspergersrules - Same deal as Troll
* https://snoonet.org/vol - I think this is now "volunteer-recruitment" - will add alias
* https://snoonet.org/community/depression/findtreatment.samhsa.gov - clearly this ain't right
* https://snoonet.org/webchat - think we'll need an nginx rewrite for this one - direct to https://webchat.snoonet.org
* https://snoonet.org/community/depression/resources - page missing

@linuxdaemon please could you retrieve the content for gonzo's staff and the depression resources page from the backups from the Ruby site, and maybe add that rewrite for webchat if you have a mo? I'll sort the other stuff in the code.

**Comment by n7st** [comment] 2019-04-14 10:01
Merged in https://github.com/snoonetIRC/static-web/commit/78340d3098d1d8ef3517bf9ca9ea1a0293b7df06

**Closed as completed by n7st** 2019-04-14 10:01 UTC
